### ISSUE TITLE
BroadcastReceiver Crashes in 2.7.0

### ISSUE THREAD

**Issue by billyking991** [taboola/taboola-android#22] opened 2020-08-22 15:49 UTC
I recently updated to Taboola Android SDK 2.7.0 and started seeing a ton of crashes in Crashlytics.  When I reverted back to 2.6.0, the crashes disappeared.  Something is 2.7.0 is causing havoc with a BroadcastReceiver crash.  Here are the stack traces:

FSDReceiver.java line 98 - 

983 crashes, 983 users
72% OS 9, 22% OS 8
98% Background
58% Samsung

Fatal Exception: java.lang.IllegalStateException: Broadcast already finished
       at android.content.BroadcastReceiver$PendingResult.sendFinished(BroadcastReceiver.java:248)
       at android.content.BroadcastReceiver$PendingResult.finish(BroadcastReceiver.java:227)
       at com.taboola.android.global_components.fsd.FSDReceiver$Task.onPostExecute(FSDReceiver.java:98)
       at com.taboola.android.global_components.fsd.FSDReceiver$Task.onPostExecute(FSDReceiver.java:28)
       at android.os.AsyncTask.finish(AsyncTask.java:695)
       at android.os.AsyncTask.-wrap1(AsyncTask.java)
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6651)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:810)

BroadcastReceiver.java line 248 - 

1.1K crashes, 1.1K users
80% OS 9, 20% OS 8
97% Background
57% Samsung

Fatal Exception: java.lang.IllegalStateException: Broadcast already finished
       at android.content.BroadcastReceiver$PendingResult.sendFinished(BroadcastReceiver.java:248)
       at android.content.BroadcastReceiver$PendingResult$1.run(BroadcastReceiver.java:221)
       at android.app.QueuedWork.processPendingWork(QueuedWork.java:258)
       at android.app.QueuedWork.access$000(QueuedWork.java:49)
       at android.app.QueuedWork$QueuedWorkHandler.handleMessage(QueuedWork.java:278)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.os.HandlerThread.run(HandlerThread.java:65)

Something happened between 2.6.0 and 2.7.0 to cause these crashes.  As soon as I reverted back to 2.6.0 in an emergency app update, the crashes disappeared.  The first stack trace is definitely from the Taboola SDK.  I'm not sure about the second one, but reverting the SDK stopped that crash as well.  

Please let me know if you need any other info from me.  Please let me know when it is safe to update to the next version.

**Comment by omriariav** [comment] 2022-10-27 07:24
Sorry for the very late reply, but the issue is fixed on the latest SDK 2.x and SDK 3.x versions

**Closed as completed by omriariav** 2022-10-27 07:24 UTC
